import type { Journey, JourneyStep } from "./types";

/**
 * Per-life-event seed journeys. Requirements are normally AI-generated and
 * cached in Supabase (see lib/server/journey-requirements.ts); this map is
 * the fallback used when the eGov AI Assistant/Supabase aren't configured or
 * a call fails, so local dev and offline use still work. Also used directly by
 * JourneyScreen when no server-prefetched journey is available (e.g. tests).
 * Users are always routed to the official page for exact amounts/requirements.
 */

type StepSeed = Omit<JourneyStep, "step_number">;

function build(
  eventId: string,
  emoji: string,
  lifeEvent: string,
  summary: string,
  seeds: StepSeed[],
): Journey {
  const steps: JourneyStep[] = seeds.map((seed, i) => ({
    ...seed,
    step_number: i + 1,
  }));
  return {
    id: `ehakbang:journey:event:${eventId}`,
    event_id: eventId,
    emoji,
    life_event: lifeEvent,
    summary,
    total_steps: steps.length,
    record_updates: steps.filter((s) => s.step_type === "record_update").length,
    benefit_claims: steps.filter((s) => s.step_type === "benefit_claim").length,
    steps,
    status: "active",
    language: "en",
    created_at: "2026-07-22T00:00:00.000Z",
    completed_at: null,
    completed_step_numbers: [],
    paid_step_numbers: [],
    field_answers: {},
  };
}

export const EVENT_JOURNEYS: Record<string, Journey> = {
  "got-married": build(
    "got-married",
    "💍",
    "Got Married",
    "Update your civil status across all agencies so your spouse is recognized.",
    [
      {
        agency_name: "Social Security System",
        agency_code: "SSS",
        step_title: "Update civil status & beneficiaries",
        step_type: "record_update",
        reason: "Ensures your spouse is recognized as a beneficiary.",
        documents_required: ["PSA marriage certificate", "UMID / SSS ID"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "SSS Member Update",
        egov_search_term: "SSS update civil status",
      },
      {
        agency_name: "Philippine Health Insurance Corporation",
        agency_code: "PHILHEALTH",
        step_title: "Add your spouse as dependent",
        step_type: "record_update",
        reason: "A non-working spouse can share your PhilHealth coverage.",
        documents_required: ["PSA marriage certificate", "PhilHealth MDR"],
        estimated_time: "Same day",
        important_note: "A non-working spouse can be a free dependent.",
        egov_service_name: "PhilHealth Dependent Update",
        egov_search_term: "PhilHealth add spouse dependent",
      },
      {
        agency_name: "Home Development Mutual Fund",
        agency_code: "PAGIBIG",
        step_title: "Update Pag-IBIG member information",
        step_type: "record_update",
        reason: "Keep civil status and beneficiaries current.",
        documents_required: ["PSA marriage certificate", "Pag-IBIG MDF"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "Pag-IBIG Member Update",
        egov_search_term: "Pag-IBIG update civil status",
      },
      {
        agency_name: "Bureau of Internal Revenue",
        agency_code: "BIR",
        step_title: "Update civil status (BIR Form 2305)",
        step_type: "record_update",
        reason: "Reflects your new civil status for correct withholding.",
        documents_required: ["PSA marriage certificate", "TIN"],
        estimated_time: "1–2 days",
        important_note: null,
        egov_service_name: "BIR Taxpayer Update",
        egov_search_term: "BIR form 2305 civil status",
      },
      {
        agency_name: "Philippine Identification System Authority",
        agency_code: "PHILSYS",
        step_title: "Update your surname on your National ID",
        step_type: "record_update",
        reason: "Keeps your National ID consistent if you're taking your spouse's surname.",
        documents_required: ["PSA marriage certificate", "Current National ID / valid ID"],
        estimated_time: "2–4 weeks",
        important_note: "Optional under Philippine law — only needed if you're changing your surname.",
        egov_service_name: "PhilSys Demographic Update",
        egov_search_term: "PhilSys national ID update surname married",
      },
    ],
  ),

  "had-a-baby": build(
    "had-a-baby",
    "👶",
    "Had a Baby",
    "Register your newborn and claim the maternity and health benefits you're entitled to.",
    [
      {
        agency_name: "Philippine Statistics Authority",
        agency_code: "PSA",
        step_title: "Register your baby's birth",
        step_type: "record_update",
        reason: "An official birth certificate is needed for most other steps.",
        documents_required: [
          "Certificate of Live Birth from the hospital",
          "Valid IDs of both parents",
        ],
        estimated_time: "1–2 weeks",
        important_note: "Register within 30 days to avoid late registration.",
        egov_service_name: "PSA Birth Registration",
        egov_search_term: "PSA birth registration",
      },
      {
        agency_name: "Philippine Health Insurance Corporation",
        agency_code: "PHILHEALTH",
        step_title: "Claim maternity & newborn benefits",
        step_type: "benefit_claim",
        reason: "Helps cover delivery and your newborn's initial care.",
        documents_required: ["PhilHealth MDR", "Birth certificate", "Hospital billing"],
        estimated_time: "At discharge or within 60 days",
        important_note: "Verify current coverage amounts on the official page.",
        egov_service_name: "PhilHealth Benefit Claim",
        egov_search_term: "PhilHealth maternity benefit claim",
      },
      {
        agency_name: "Social Security System",
        agency_code: "SSS",
        step_title: "Claim your SSS maternity benefit",
        step_type: "benefit_claim",
        reason: "Contributing members may receive a cash maternity benefit.",
        documents_required: ["SSS Maternity Notification", "Birth certificate", "UMID"],
        estimated_time: "2–4 weeks",
        important_note: "Amount depends on contributions — verify officially.",
        egov_service_name: "SSS Maternity Benefit",
        egov_search_term: "SSS maternity benefit",
      },
      {
        agency_name: "Philippine Health Insurance Corporation",
        agency_code: "PHILHEALTH",
        step_title: "Add your newborn as dependent",
        step_type: "record_update",
        reason: "Extends your PhilHealth coverage to your baby.",
        documents_required: ["Birth certificate", "PhilHealth update form"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "PhilHealth Dependent Update",
        egov_search_term: "PhilHealth add dependent",
      },
      {
        agency_name: "Home Development Mutual Fund",
        agency_code: "PAGIBIG",
        step_title: "Update your Pag-IBIG beneficiaries",
        step_type: "record_update",
        reason: "Keeps your savings and benefits directed to your family.",
        documents_required: ["Birth certificate", "Pag-IBIG MDF"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "Pag-IBIG Member Update",
        egov_search_term: "Pag-IBIG update beneficiaries",
      },
    ],
  ),

  "lost-a-job": build(
    "lost-a-job",
    "💼",
    "Lost a Job",
    "Claim the unemployment support you're entitled to and keep your memberships active.",
    [
      {
        agency_name: "Social Security System",
        agency_code: "SSS",
        step_title: "Claim SSS Unemployment Benefit",
        step_type: "benefit_claim",
        reason: "Involuntarily separated members may claim cash support.",
        documents_required: ["DOLE Certificate of Involuntary Separation", "UMID"],
        estimated_time: "2–4 weeks",
        important_note: "File within one year of separation.",
        egov_service_name: "SSS Unemployment Benefit",
        egov_search_term: "SSS unemployment benefit",
      },
      {
        agency_name: "Department of Labor and Employment",
        agency_code: "DOLE",
        step_title: "Register for job matching / livelihood",
        step_type: "benefit_claim",
        reason: "Access DOLE job matching and livelihood assistance.",
        documents_required: ["Valid ID", "Resume (optional)"],
        estimated_time: "Same day",
        important_note: "Programs vary — check current availability.",
        egov_service_name: "DOLE PhilJobNet",
        egov_search_term: "DOLE PhilJobNet registration",
      },
      {
        agency_name: "Philippine Health Insurance Corporation",
        agency_code: "PHILHEALTH",
        step_title: "Shift to Direct Contributor",
        step_type: "record_update",
        reason: "Keeps your health coverage active after employment ends.",
        documents_required: ["PhilHealth MDR", "Valid ID"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "PhilHealth Membership Update",
        egov_search_term: "PhilHealth direct contributor",
      },
      {
        agency_name: "Home Development Mutual Fund",
        agency_code: "PAGIBIG",
        step_title: "Continue as Voluntary Member",
        step_type: "record_update",
        reason: "Maintains your Pag-IBIG savings and loan eligibility.",
        documents_required: ["Pag-IBIG MID", "Valid ID"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "Pag-IBIG Membership Update",
        egov_search_term: "Pag-IBIG voluntary member",
      },
    ],
  ),

  retired: build(
    "retired",
    "🏖️",
    "Retired",
    "Claim your pension and provident benefits and convert your memberships.",
    [
      {
        agency_name: "Social Security System / GSIS",
        agency_code: "SSS",
        step_title: "File your retirement pension",
        step_type: "benefit_claim",
        reason: "Qualified retirees receive a monthly pension or lump sum.",
        documents_required: ["UMID / GSIS eCard", "Birth certificate", "Bank account"],
        estimated_time: "4–8 weeks",
        important_note: "Amount depends on contributions/service — verify officially.",
        egov_service_name: "SSS/GSIS Retirement Claim",
        egov_search_term: "SSS retirement pension",
      },
      {
        agency_name: "Home Development Mutual Fund",
        agency_code: "PAGIBIG",
        step_title: "Claim your Pag-IBIG provident benefit",
        step_type: "benefit_claim",
        reason: "Retirement is a valid ground to claim your total savings.",
        documents_required: ["Pag-IBIG MID", "Valid ID", "Claim form"],
        estimated_time: "2–4 weeks",
        important_note: null,
        egov_service_name: "Pag-IBIG Provident Claim",
        egov_search_term: "Pag-IBIG provident benefit claim",
      },
      {
        agency_name: "Philippine Health Insurance Corporation",
        agency_code: "PHILHEALTH",
        step_title: "Convert to Lifetime Member",
        step_type: "record_update",
        reason: "Retirees with enough contributions get free lifetime coverage.",
        documents_required: ["PhilHealth MDR", "Proof of contributions"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "PhilHealth Lifetime Member",
        egov_search_term: "PhilHealth lifetime member",
      },
      {
        agency_name: "Social Security System / GSIS",
        agency_code: "SSS",
        step_title: "Update member records & beneficiaries",
        step_type: "record_update",
        reason: "Ensure pension and survivorship details are correct.",
        documents_required: ["Valid ID", "Updated beneficiary list"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "SSS/GSIS Member Update",
        egov_search_term: "SSS update beneficiaries",
      },
    ],
  ),

  "started-a-business": build(
    "started-a-business",
    "🏪",
    "Started a Business",
    "Register your business with the right agencies so you can operate legally.",
    [
      {
        agency_name: "Department of Trade and Industry",
        agency_code: "DTI",
        step_title: "Register your business name",
        step_type: "record_update",
        reason: "Sole proprietors must register their business name (SEC for corporations).",
        documents_required: ["Valid ID"],
        estimated_time: "Same day (online)",
        important_note: null,
        egov_service_name: "DTI Business Name Registration",
        egov_search_term: "DTI business name registration",
        required_fields: [
          {
            field_key: "proposed_business_name",
            label: "Proposed business name",
            field_type: "text",
            hint: "DTI checks availability -- have a backup name ready.",
            required: true,
          },
        ],
      },
      {
        agency_name: "Bureau of Internal Revenue",
        agency_code: "BIR",
        step_title: "Register with the BIR",
        step_type: "record_update",
        reason: "Get your Certificate of Registration and official receipts.",
        documents_required: ["DTI certificate", "Valid ID", "BIR Form 1901"],
        estimated_time: "1–3 days",
        important_note: null,
        egov_service_name: "BIR Business Registration",
        egov_search_term: "BIR business registration 1901",
      },
      {
        agency_name: "Local Government Unit",
        agency_code: "LGU",
        step_title: "Get your Mayor's / Business Permit",
        step_type: "record_update",
        reason: "Required to legally operate within the locality.",
        documents_required: ["DTI certificate", "Barangay clearance"],
        estimated_time: "3–7 days",
        important_note: null,
        egov_service_name: "LGU Business Permit",
        egov_search_term: "LGU business permit",
        required_fields: [
          {
            field_key: "lease_site_details",
            label: "Business address / lease or site details",
            field_type: "text",
            hint: "The exact address where the business will operate.",
            required: true,
          },
        ],
      },
      {
        agency_name: "SSS / PhilHealth / Pag-IBIG",
        agency_code: "SSS",
        step_title: "Register as an employer",
        step_type: "record_update",
        reason: "Required once you hire employees.",
        documents_required: ["Business registration", "Valid ID"],
        estimated_time: "1–3 days",
        important_note: null,
        egov_service_name: "Employer Registration",
        egov_search_term: "SSS employer registration",
      },
    ],
  ),

  "became-senior": build(
    "became-senior",
    "🧓",
    "Became a Senior Citizen",
    "Claim your senior citizen ID and the benefits and pension you qualify for.",
    [
      {
        agency_name: "Office for Senior Citizens Affairs",
        agency_code: "OSCA",
        step_title: "Get your Senior Citizen ID & booklet",
        step_type: "record_update",
        reason: "Unlocks legally mandated senior discounts and privileges.",
        documents_required: ["PSA birth certificate", "Valid ID", "Proof of residence"],
        estimated_time: "Same day–1 week",
        important_note: null,
        egov_service_name: "OSCA Senior Citizen ID",
        egov_search_term: "OSCA senior citizen ID",
      },
      {
        agency_name: "Philippine Health Insurance Corporation",
        agency_code: "PHILHEALTH",
        step_title: "Confirm senior citizen coverage",
        step_type: "record_update",
        reason: "Senior citizens are automatically covered under the law.",
        documents_required: ["Senior Citizen ID", "PhilHealth MDR"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "PhilHealth Senior Coverage",
        egov_search_term: "PhilHealth senior citizen coverage",
      },
      {
        agency_name: "Department of Social Welfare and Development",
        agency_code: "DSWD",
        step_title: "Apply for Social Pension (if qualified)",
        step_type: "benefit_claim",
        reason: "Indigent seniors receive a monthly social pension.",
        documents_required: ["Senior Citizen ID", "Proof of indigency"],
        estimated_time: "Subject to validation",
        important_note: "Eligibility is means-tested — verify with your LGU/DSWD.",
        egov_service_name: "DSWD Social Pension",
        egov_search_term: "DSWD social pension senior",
      },
      {
        agency_name: "Social Security System / GSIS",
        agency_code: "SSS",
        step_title: "Claim your pension (if a member)",
        step_type: "benefit_claim",
        reason: "Members aged 60+ may start their retirement pension.",
        documents_required: ["UMID / GSIS eCard", "Bank account"],
        estimated_time: "4–8 weeks",
        important_note: "Verify amount and eligibility officially.",
        egov_service_name: "SSS/GSIS Pension Claim",
        egov_search_term: "SSS retirement pension senior",
      },
    ],
  ),

  "became-pwd": build(
    "became-pwd",
    "♿",
    "Became a PWD",
    "Register as a PWD to access your ID, coverage, and assistance.",
    [
      {
        agency_name: "PDAO / Local Government Unit",
        agency_code: "LGU",
        step_title: "Register for your PWD ID",
        step_type: "record_update",
        reason: "Unlocks legally mandated PWD discounts and privileges.",
        documents_required: ["Medical certificate", "Valid ID", "Photo"],
        estimated_time: "Same day–1 week",
        important_note: null,
        egov_service_name: "PWD ID Registration",
        egov_search_term: "PWD ID registration",
      },
      {
        agency_name: "Philippine Health Insurance Corporation",
        agency_code: "PHILHEALTH",
        step_title: "Confirm PhilHealth coverage as PWD",
        step_type: "record_update",
        reason: "PWDs are covered under national health insurance.",
        documents_required: ["PWD ID", "PhilHealth MDR"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "PhilHealth PWD Coverage",
        egov_search_term: "PhilHealth PWD coverage",
      },
      {
        agency_name: "Department of Social Welfare and Development",
        agency_code: "DSWD",
        step_title: "Access PWD assistance & discount booklet",
        step_type: "benefit_claim",
        reason: "Provides purchase booklets and possible assistance programs.",
        documents_required: ["PWD ID", "Valid ID"],
        estimated_time: "Same day",
        important_note: "Programs vary by LGU — verify locally.",
        egov_service_name: "DSWD / LGU PWD Assistance",
        egov_search_term: "PWD assistance booklet",
      },
      {
        agency_name: "Social Security System / GSIS",
        agency_code: "SSS",
        step_title: "Claim disability benefit (if a member)",
        step_type: "benefit_claim",
        reason: "Members with disability may qualify for a benefit.",
        documents_required: ["Medical records", "UMID / GSIS eCard"],
        estimated_time: "4–8 weeks",
        important_note: "Verify eligibility and amount officially.",
        egov_service_name: "SSS/GSIS Disability Benefit",
        egov_search_term: "SSS disability benefit",
      },
    ],
  ),

  "death-in-family": build(
    "death-in-family",
    "🕊️",
    "Death in the Family",
    "Process the death certificate and claim the survivor and funeral benefits due.",
    [
      {
        agency_name: "Philippine Statistics Authority",
        agency_code: "PSA",
        step_title: "Register the death certificate",
        step_type: "record_update",
        reason: "Required before most benefits can be claimed.",
        documents_required: ["Medical certificate of death", "Valid IDs"],
        estimated_time: "1–2 weeks",
        important_note: "Register promptly to avoid late-registration steps.",
        egov_service_name: "PSA Death Certificate",
        egov_search_term: "PSA death certificate registration",
      },
      {
        agency_name: "Social Security System / GSIS",
        agency_code: "SSS",
        step_title: "Claim the funeral benefit",
        step_type: "benefit_claim",
        reason: "A funeral grant is provided to whoever paid for the burial.",
        documents_required: ["Death certificate", "Funeral receipts", "Claimant ID"],
        estimated_time: "2–4 weeks",
        important_note: "Verify the current grant amount officially.",
        egov_service_name: "SSS/GSIS Funeral Benefit",
        egov_search_term: "SSS funeral benefit",
      },
      {
        agency_name: "Social Security System / GSIS",
        agency_code: "SSS",
        step_title: "File for survivorship pension",
        step_type: "benefit_claim",
        reason: "Qualified beneficiaries may receive a monthly pension.",
        documents_required: ["Death certificate", "Marriage/birth certificates", "IDs"],
        estimated_time: "4–8 weeks",
        important_note: "Eligibility depends on the member's record.",
        egov_service_name: "SSS/GSIS Survivorship Pension",
        egov_search_term: "SSS survivorship pension",
      },
      {
        agency_name: "Home Development Mutual Fund",
        agency_code: "PAGIBIG",
        step_title: "Claim Pag-IBIG death/provident benefit",
        step_type: "benefit_claim",
        reason: "Beneficiaries may claim the member's provident savings.",
        documents_required: ["Death certificate", "Beneficiary IDs", "Claim form"],
        estimated_time: "2–4 weeks",
        important_note: null,
        egov_service_name: "Pag-IBIG Death Benefit",
        egov_search_term: "Pag-IBIG death benefit claim",
      },
    ],
  ),

  "just-graduated": build(
    "just-graduated",
    "🎓",
    "Just Graduated",
    "Set up your government IDs and memberships as you prepare for your first job.",
    [
      {
        agency_name: "Bureau of Internal Revenue",
        agency_code: "BIR",
        step_title: "Get your TIN",
        step_type: "record_update",
        fulfills_id: "tin",
        reason: "A Tax Identification Number is required for employment.",
        documents_required: ["PSA birth certificate", "Valid ID"],
        estimated_time: "1–2 days",
        important_note: null,
        egov_service_name: "BIR TIN Registration",
        egov_search_term: "BIR TIN registration",
      },
      {
        agency_name: "Social Security System",
        agency_code: "SSS",
        step_title: "Register for your SSS number",
        step_type: "record_update",
        fulfills_id: "sss",
        reason: "Your SSS number follows you across every employer.",
        documents_required: ["PSA birth certificate", "Valid ID"],
        estimated_time: "Same day (online)",
        important_note: null,
        egov_service_name: "SSS Number Registration",
        egov_search_term: "SSS number registration",
      },
      {
        agency_name: "PhilHealth / Pag-IBIG",
        agency_code: "PHILHEALTH",
        step_title: "Register with PhilHealth & Pag-IBIG",
        step_type: "record_update",
        fulfills_id: "philhealth",
        reason: "Basic memberships you'll need once employed.",
        documents_required: ["PSA birth certificate", "Valid ID"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "PhilHealth & Pag-IBIG Registration",
        egov_search_term: "PhilHealth Pag-IBIG registration",
      },
      {
        agency_name: "Department of Labor and Employment",
        agency_code: "DOLE",
        step_title: "Register for job matching",
        step_type: "benefit_claim",
        reason: "Access job listings and DOLE programs for new graduates.",
        documents_required: ["Resume", "Valid ID"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "DOLE PhilJobNet",
        egov_search_term: "DOLE PhilJobNet registration",
      },
    ],
  ),

  "first-job": build(
    "first-job",
    "🧑‍💼",
    "Started First Job",
    "Complete the government registrations your first employer will require.",
    [
      {
        agency_name: "Bureau of Internal Revenue",
        agency_code: "BIR",
        step_title: "Get / update your TIN",
        step_type: "record_update",
        fulfills_id: "tin",
        reason: "Required for tax withholding by your employer.",
        documents_required: ["PSA birth certificate", "Valid ID", "BIR Form 1902"],
        estimated_time: "1–2 days",
        important_note: null,
        egov_service_name: "BIR TIN (Form 1902)",
        egov_search_term: "BIR form 1902 employee",
      },
      {
        agency_name: "Social Security System",
        agency_code: "SSS",
        step_title: "Register your SSS number",
        step_type: "record_update",
        fulfills_id: "sss",
        reason: "Enables your contributions and future benefits.",
        documents_required: ["PSA birth certificate", "Valid ID"],
        estimated_time: "Same day (online)",
        important_note: null,
        egov_service_name: "SSS Number Registration",
        egov_search_term: "SSS number registration",
      },
      {
        agency_name: "Philippine Health Insurance Corporation",
        agency_code: "PHILHEALTH",
        step_title: "Register with PhilHealth",
        step_type: "record_update",
        fulfills_id: "philhealth",
        reason: "Provides your national health insurance coverage.",
        documents_required: ["PSA birth certificate", "Valid ID"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "PhilHealth Registration",
        egov_search_term: "PhilHealth member registration",
      },
      {
        agency_name: "Home Development Mutual Fund",
        agency_code: "PAGIBIG",
        step_title: "Register with Pag-IBIG",
        step_type: "record_update",
        fulfills_id: "pagibig",
        reason: "Enables savings and future housing loan eligibility.",
        documents_required: ["Valid ID"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "Pag-IBIG Registration",
        egov_search_term: "Pag-IBIG member registration",
      },
    ],
  ),

  "moved-residence": build(
    "moved-residence",
    "🏠",
    "Moved Residence",
    "Update your address and voter registration to match your new home.",
    [
      {
        agency_name: "Commission on Elections",
        agency_code: "COMELEC",
        step_title: "Transfer your voter registration",
        step_type: "record_update",
        reason: "Lets you vote in your new city/municipality.",
        documents_required: ["Valid ID", "Proof of new address"],
        estimated_time: "Subject to registration schedule",
        important_note: "Only during COMELEC registration periods.",
        egov_service_name: "COMELEC Voter Transfer",
        egov_search_term: "COMELEC transfer registration",
      },
      {
        agency_name: "Local Government Unit / Barangay",
        agency_code: "LGU",
        step_title: "Update your barangay residency",
        step_type: "record_update",
        reason: "Establishes residency for local services and clearances.",
        documents_required: ["Valid ID", "Proof of new address"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "Barangay Residency Update",
        egov_search_term: "barangay certificate of residency",
      },
      {
        agency_name: "SSS / PhilHealth / Pag-IBIG",
        agency_code: "SSS",
        step_title: "Update your address on file",
        step_type: "record_update",
        reason: "Keeps your contribution records and mail accurate.",
        documents_required: ["Valid ID", "Proof of new address"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "Member Address Update",
        egov_search_term: "SSS update address",
      },
      {
        agency_name: "PhilSys / Land Transportation Office",
        agency_code: "LTO",
        step_title: "Update National ID & driver's license address",
        step_type: "record_update",
        reason: "Keeps your primary IDs consistent with your residence.",
        documents_required: ["National ID / license", "Proof of new address"],
        estimated_time: "1–3 days",
        important_note: null,
        egov_service_name: "PhilSys / LTO Address Update",
        egov_search_term: "update national ID address",
      },
    ],
  ),
  annulment: build(
    "annulment",
    "⚖️",
    "Annulment",
    "Update your civil status back to single across all agencies now that your marriage has been annulled.",
    [
      {
        agency_name: "Philippine Statistics Authority",
        agency_code: "PSA",
        step_title: "Annotate your marriage certificate",
        step_type: "record_update",
        reason: "The court decree must be annotated on your PSA marriage record before other agencies will recognize it.",
        documents_required: ["Court Decree of Annulment", "Certificate of Finality"],
        estimated_time: "2–6 weeks",
        important_note: null,
        egov_service_name: "PSA Certificate Annotation",
        egov_search_term: "PSA annotate marriage certificate annulment",
      },
      {
        agency_name: "Social Security System",
        agency_code: "SSS",
        step_title: "Update civil status & beneficiaries",
        step_type: "record_update",
        reason: "Reverts your recognized civil status and beneficiary records to single.",
        documents_required: ["PSA-annotated marriage certificate", "UMID / SSS ID"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "SSS Member Update",
        egov_search_term: "SSS update civil status",
      },
      {
        agency_name: "Philippine Health Insurance Corporation",
        agency_code: "PHILHEALTH",
        step_title: "Remove your former spouse as dependent",
        step_type: "record_update",
        reason: "Keeps your PhilHealth dependents accurate after the annulment.",
        documents_required: ["PSA-annotated marriage certificate", "PhilHealth MDR"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "PhilHealth Dependent Update",
        egov_search_term: "PhilHealth remove dependent",
      },
      {
        agency_name: "Home Development Mutual Fund",
        agency_code: "PAGIBIG",
        step_title: "Update Pag-IBIG member information",
        step_type: "record_update",
        reason: "Keep civil status and beneficiaries current.",
        documents_required: ["PSA-annotated marriage certificate", "Pag-IBIG MDF"],
        estimated_time: "Same day",
        important_note: null,
        egov_service_name: "Pag-IBIG Member Update",
        egov_search_term: "Pag-IBIG update civil status",
      },
      {
        agency_name: "Bureau of Internal Revenue",
        agency_code: "BIR",
        step_title: "Update civil status (BIR Form 2305)",
        step_type: "record_update",
        reason: "Reflects your new civil status for correct withholding.",
        documents_required: ["PSA-annotated marriage certificate", "TIN"],
        estimated_time: "1–2 days",
        important_note: null,
        egov_service_name: "BIR Taxpayer Update",
        egov_search_term: "BIR form 2305 civil status",
      },
      {
        agency_name: "Philippine Identification System Authority",
        agency_code: "PHILSYS",
        step_title: "Revert your surname on your National ID",
        step_type: "record_update",
        reason: "Keeps your National ID consistent if you're reverting to your maiden/former surname.",
        documents_required: ["PSA-annotated marriage certificate", "Current National ID / valid ID"],
        estimated_time: "2–4 weeks",
        important_note: "Optional under Philippine law — only needed if you're changing your surname back.",
        egov_service_name: "PhilSys Demographic Update",
        egov_search_term: "PhilSys national ID update surname annulment",
      },
    ],
  ),
};

/** Journey for a selected life-event id (e.g., from `/journey?event=...`). */
export function getJourneyByEventId(eventId: string): Journey | undefined {
  return EVENT_JOURNEYS[eventId];
}

/** Look up an event journey by its full journey id. */
export function getEventJourneyById(journeyId: string): Journey | undefined {
  return Object.values(EVENT_JOURNEYS).find((j) => j.id === journeyId);
}
