/**
 * eHakbang data model.
 *
 * The `JourneyStep` and generated journey fields originally mirrored the
 * Claude API response schema sketched in the PRD (§9.1.2); requirements are
 * now generated by OpenAI's Responses API with web search (see
 * `lib/server/journey-requirements.ts`) and cached in Supabase. App-level
 * fields (id, status, dates, completion) are layered on top for the UI and
 * localStorage.
 */

/** A step is either a legal record update or a benefit the citizen can claim. */
export type StepType = "record_update" | "benefit_claim";

/** Lifecycle of a journey within the app. */
export type JourneyStatus = "active" | "completed" | "archived";

/** UI + Claude prompt language preference. */
export type Language = "fil" | "en";

/**
 * Government-issued IDs / memberships a citizen can hold in their ID wallet.
 * Used to auto-satisfy journey steps whose purpose is to obtain that ID.
 */
export type IdType =
  | "tin"
  | "sss"
  | "philhealth"
  | "pagibig"
  | "umid"
  | "philsys"
  | "passport"
  | "drivers-license"
  | "voters-id"
  | "prc";

/** Input type for a step's citizen-supplied `RequiredField`. */
export type RequiredFieldType = "text" | "number" | "date";

/**
 * A data value only the citizen knows and must type in -- distinct from
 * `documents_required`, which lists things to upload. E.g. a proposed
 * business name or a bank account number isn't satisfied by any document.
 */
export interface RequiredField {
  /** Machine-safe key, e.g. "proposed_business_name". */
  field_key: string;
  /** Human-readable prompt shown to the user. */
  label: string;
  field_type: RequiredFieldType;
  /** Short format/help text. Null when there's none. */
  hint?: string | null;
  required: boolean;
}

/**
 * Government fee info for a step. `amount` is AI-generated free text (e.g.
 * "₱500", "Free", "₱200–500 depending on LGU") -- see `lib/journey-fees.ts`
 * for how it's conservatively parsed into a payable total for the eGovPay
 * integration (see eGovPay-apidoc.md).
 */
export interface StepFee {
  /** Free-text amount, e.g. "₱500", "Free", "₱200–500 depending on LGU" -- gov fees aren't always fixed. */
  amount: string;
  currency: string;
  /** Where/how to pay, e.g. "Pay at the SSS branch cashier upon filing." */
  how_to_pay: string;
  /** Citation URL the fee was found on, distinct from egov_url. */
  official_source_url?: string | null;
}

/** One ordered government action. Mirrors PRD §9.1.2 `steps[]`. */
export interface JourneyStep {
  step_number: number;
  agency_name: string;
  /** Short agency code, e.g. SSS, PHILHEALTH, PSA, PAGIBIG, BIR, DOLE, GSIS, DSWD. */
  agency_code: string;
  step_title: string;
  step_type: StepType;
  /** Plain-language explanation of why this step is needed. */
  reason: string;
  documents_required: string[];
  /** e.g. "1-2 weeks processing". */
  estimated_time: string;
  /** Warnings, deadlines, or conditions. Null when none. */
  important_note: string | null;
  /** Government fee for this step, when one exists. Null/absent when free. */
  fee?: StepFee | null;
  egov_service_name: string;
  /** Term used to look up the official URL in the eGov catalog. */
  egov_search_term: string;
  /**
   * Agency-specific data values the citizen must supply beyond the single
   * evidence document (e.g. a proposed business name, a bank account
   * number). Absent/empty when the document alone is sufficient.
   */
  required_fields?: RequiredField[];
  /**
   * Resolved official service URL (from the eGov catalog API later).
   * Optional in the UI-only phase — falls back to the agency homepage.
   */
  egov_url?: string;
  /**
   * When set, completing this step obtains/updates the given government ID.
   * If the citizen already holds that ID in their ID wallet, the step is
   * auto-satisfied (marked done dynamically without manual action).
   */
  fulfills_id?: IdType;
}

/**
 * A complete journey. The `life_event`..`steps` fields match the generated
 * Claude schema (PRD §9.1.2); the rest is app state.
 */
export interface Journey {
  /** Stable id, e.g. `ehakbang:journey:{timestamp}` in localStorage later. */
  id: string;
  /** Source life-event id, when the journey came from a predefined event. */
  event_id?: string;
  /** Emoji shown in the archive list and headers (UI convenience). */
  emoji: string;
  /** Normalized life event label. */
  life_event: string;
  /** 1–2 sentence plain-language summary of the journey. */
  summary: string;
  total_steps: number;
  record_updates: number;
  benefit_claims: number;
  steps: JourneyStep[];
  status: JourneyStatus;
  language: Language;
  /** ISO date string of creation. */
  created_at: string;
  /** ISO date string of completion, or null while active. */
  completed_at: string | null;
  /** Step numbers the user has marked as done. */
  completed_step_numbers: number[];
  /** Step numbers whose government fee has been paid via eGovPay. */
  paid_step_numbers: number[];
  /** Citizen-supplied answers to steps' `required_fields`, keyed by step_number then field_key. */
  field_answers: Record<number, Record<string, string>>;
  /**
   * Step numbers completed via the mocked Auto Apply queue (see
   * lib/server/application-queue.ts) -- a subset of completed_step_numbers.
   * Distinct from steps completed by other means (wallet auto-satisfy, the
   * bulk AutoApplyBanner/ApplyAllModal flows), which don't produce a physical
   * document to claim in person.
   */
  auto_applied_step_numbers: number[];
  /** Auto-applied step numbers whose resulting document has been claimed at the agency office. */
  claimed_step_numbers: number[];
}

/** A predefined life-event shortcut card shown on the landing screen. */
export interface LifeEvent {
  id: string;
  emoji: string;
  /** Short Filipino label. */
  label: string;
  /** English sub-label. */
  sublabel: string;
  /** Very short caption for compact tiles (e.g., "Baby", "Married"). */
  short: string;
  /** Natural-language text used to populate the input / journey generation. */
  description: string;
  /** True for the primary 8 cards; false for "More events". */
  common: boolean;
}
